[pyprland]
plugins = [
  "scratchpads",
  "lost_windows",
  "monitors",
  "fetch_client_menu",
  "workspaces_follow_focus",
]

[monitors.placement]
"Acer".top_center_of = "Sony"

[workspaces_follow_focus]
max_workspaces = 9

[fetch_client_menu]
engine = "wofi"

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
