# Just comment a section if you want to disable it
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$conda\
$python\
$memory_usage\
$custom\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

right_format = """
$time\
"""
[custom]
disabled = true

[memory_usage]
disabled = true

[git_metrics]
disabled = true

# [character]
# success_symbol = "[➜](bold green)" 

# [git_status]
# not working on kitty atm?
# diverged = " $count "
## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [╭─$user]($style)@"
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold dimmed red"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false


## SECOND LINE/ROW: Prompt
# Somethere at the beginning
[battery]
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
disabled = true

[[battery.display]] # "bold red" style when capacity is between 0% and 10%
threshold = 15
style = "bold red"
disabled = true

[[battery.display]] # "bold yellow" style when capacity is between 10% and 30%
threshold = 50
style = "bold yellow"
disabled = true

[[battery.display]] # "bold green" style when capacity is between 10% and 30%
threshold = 80
style = "bold green"
disabled = true

# Prompt: optional param 1
[time]
format = " 🕙 $time($style)\n"
time_format = "%T"
style = "bold blue"
disabled = false

# Prompt: param 2 └─
[character]
success_symbol = " [╰─λ](bold red)"
error_symbol = " [×](bold red)"
# use_symbol_for_status = true

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[jobs]
number_threshold = 3
disabled = true

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

# [git_branch]
# symbol = " "

[golang]
symbol = " "

# [haskell]
# symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
